### ISSUE TITLE
addrelease's file creation is broken on Python 3

### ISSUE THREAD

**Issue by Freso** [metabrainz/picard-plugins#101]
When trying to create the temporary file for the HTML form, Python throws an exception:
```python-traceback
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/picard/ui/itemviews.py", line 46, in __callback
    self.callback(objs)
  File "/home/freso/.config/MusicBrainz/Picard/plugins/addrelease.py", line 109, in callback
    html_file = self.generate_html_file(self.form_values)
  File "/home/freso/.config/MusicBrainz/Picard/plugins/addrelease.py", line 92, in generate_html_file
    f.write(HTML_HEAD % (self.NAME, mbserver_url(self.submit_path)))
  File "/usr/lib/python3.6/codecs.py", line 377, in write
    self.stream.write(data)
TypeError: write() argument must be str, not bytes
```

**Comment by Freso** [comment]
Merged into 2.0 branch.
